;;===============================
;;Name: ALLISON SOMMERS
;;===============================

.orig x3000
	LD R6, STACK	; LOAD THE STACK POINTER

	LD R0, N	; SET R0 = N
	ADD R6, R6, -1	; PUSH N ON STACK
	STR R0, R6, 0			

	JSR POWERSOF2	; JUMP TO POWERSOF TWO

	; AFTER EVERYTHING RECURSION -- PICKING UP ANSWER AND HANDING IT TO THE VARIABLE
	
	LDR R0, R6, 0	; LOAD RETURN VARIABLE, SHOULD BE ON TOP OF STACK
	ADD R6, R6, 2 	; RESTORE STACK POINTER TO PREVIOUS VALUE

	ST R0, ANSWER	; STORE THE ANSWER IN CORRECT VARIABLE
	HALT

N 		.fill 1
ANSWER 	.blkw 1
STACK 	.fill xF000


POWERSOF2
	ADD R6, R6, -3	; MOVE STACK UP 3
	STR R7, R6, 1	; STORE RETURN ADDRESS
	STR R5, R6, 0	; STORE OLD FP
	ADD R5, R6, -1	; NEW FP
	ADD R6, R6, -2	; 2 LOCAL VARIABLES ALLOCATION
	
	LDR R1, R5, 4			
	
	BRz ELSENIS0	; CHECK IF N == 0

	ADD R1, R1, -1
	BRz ELSENIS1	; CHECK IF N == 1

	BRp ELSE
	
	BR RETURN

ELSENIS0
	; N == 0, RETURN 1

	AND R1, R1, 0

	STR R1, R6, 0	; TEMP2 IS 0
	STR R1, R6, 1	; TEMP1 IS 0

	AND R2, R2, 0	; DEAL WITH RETURN VALUE
	ADD R2, R2, 1
	STR R2, R5, 3	
	BR RETURN

ELSENIS1
	; N == 1, RETURN 2

	AND R1, R1, 0

	STR R1, R6, 0	; TEMP2 IS 0
	STR R1, R6, 1	; TEMP1 IS 0

	AND R2, R2, 0	; DEAL WITH RETURN VALUE
	ADD R2, R2, 2
	STR R2, R5, 3	
	BR RETURN

ELSE
	ADD R6, R6, -1	; ALLOCATE FOR TEMP1
	LDR R1, R5, 4	; GET N FROM STACK
	ADD R1, R1, -1	; N--
	STR R1, R6, 0	; SHOVE N-- IN STACK
	JSR POWERSOF2

	LDR R2, R6, 0	; GET RETURN VALUE FROM STACKSPACE
	STR R2, R5, 0	; PUT TEMP1 IN REGISTER

	ADD R6, R6, -1	; ALLOCATE FOR TEMP2
	LDR R1, R5, 4	; GET N FROM THE STACK
	ADD R1, R1, -2	; N - 2
	STR R1, R6, 0	; SHOVE N - 2 IN THE STACK
	JSR POWERSOF2

	LDR R2, R6, 0	; LOAD RETURN VAL
	STR R2, R5, -1	; TEMP2 STORE IN LOCAL

	AND R1, R1, 0			
	AND R0, R0, 0		

	LDR R1, R6, 2	; GET TEMP1
	ADD R0, R0, R1
	ADD R1, R1, R1	; 3*TEMP1
	ADD R1, R1, R0			
	ADD R2, R2, R2	; 2*TEMP2

	NOT R2, R2	; TWO'S COMPLEMENT NEGATION
	ADD R2, R2, 1			

	ADD R1, R1, R2	; 3*TEMP1 - 2*TEMP2
	STR R1, R5, 3	; STORE IN RETURN VALUE (STACK)

RETURN
	ADD R6, R5, 3	; POINTER POINTS TO RETURN VALUE
	LDR R7, R5, 2	; RESTORE THE RETURN ADDRESS
	LDR R5, R5, 1	; RESTORE OLD FP
	RET

.end

